language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install

script:
  - php data/bin/check_configuration.php
  - php -dshort_open_tag=Off -dmagic_quotes_gpc=Off data/bin/symfony symfony:test --trace
