language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.3
          dist: precise
          sudo: required
        - php: 5.4
          dist: precise
          sudo: required

# faster builds on new travis setup not using sudo
sudo: false

services:
    - memcached

# cache vendor dirs
cache:
    directories:
        - lib/vendor/swiftmailer
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    # by default, --remote is not used on travis
    - git submodule update --remote --force
    - composer install

script:
    - php data/bin/check_configuration.php
    - php data/bin/symfony symfony:test --trace
